{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib) mkEnableOption mkIf mkOption types;
  tomlFormat = pkgs.formats.toml { };
  tomlLib = import ../../lib/toml.nix { inherit lib; };
  cfg = config.programs.lore;
  repositoryType = types.submodule {
    options = {
      path = mkOption {
        type = types.path;
        description = "Repository working-tree path whose .lore/config.toml is managed.";
      };
      owner = mkOption {
        type = types.str;
        default = "root";
        description = "Owner for the repository .lore directory and config.";
      };
      group = mkOption {
        type = types.str;
        default = "root";
        description = "Group for the repository .lore directory and config.";
      };
      config = mkOption {
        type = types.attrsOf types.anything;
        default = { };
        description = "Exact TOML contents for .lore/config.toml.";
      };
    };
  };

  cliToml = tomlFormat.generate "lore-cli.toml" (tomlLib.filterNulls cfg.settings);
  managedRepositories = lib.mapAttrsToList (
    name: repo:
    let
      repoToml = tomlFormat.generate "lore-${name}-repository.toml" (tomlLib.filterNulls repo.config);
    in
    ''
      install -d -m 0755 -o ${lib.escapeShellArg repo.owner} -g ${lib.escapeShellArg repo.group} ${lib.escapeShellArg "${repo.path}/.lore"}
      install -m 0644 -o ${lib.escapeShellArg repo.owner} -g ${lib.escapeShellArg repo.group} ${repoToml} ${lib.escapeShellArg "${repo.path}/.lore/config.toml"}
    ''
  ) cfg.repositories;
in
{
  options.programs.lore = {
    enable = mkEnableOption "Lore CLI";

    package = mkOption {
      type = types.nullOr types.package;
      default = pkgs.lore or null;
      defaultText = lib.literalExpression "pkgs.lore";
      description = "Lore CLI package.";
    };

    enableCompletions = mkOption {
      type = types.bool;
      default = true;
      description = "Install shell completions generated by the Lore CLI.";
    };

    settings.pager = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Pager written to the user-level cli.toml.";
    };

    repositories = mkOption {
      type = types.attrsOf repositoryType;
      default = { };
      description = "Managed repository .lore/config.toml presets. Declared files are overwritten on rebuild.";
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.package != null;
        message = "programs.lore.package must be set when pkgs.lore is not available.";
      }
    ];

    environment.systemPackages = [ cfg.package ];

    environment.etc."xdg/lore/cli.toml".source = cliToml;

    environment.etc."bash_completion.d/lore".source = mkIf cfg.enableCompletions (
      pkgs.runCommand "lore-bash-completion" { nativeBuildInputs = [ cfg.package ]; } ''
        lore completions bash > "$out"
      ''
    );

    environment.etc."zsh/site-functions/_lore".source = mkIf cfg.enableCompletions (
      pkgs.runCommand "lore-zsh-completion" { nativeBuildInputs = [ cfg.package ]; } ''
        lore completions zsh > "$out"
      ''
    );

    system.activationScripts.loreRepositories = lib.stringAfter [ "users" ] (lib.concatStringsSep "\n" managedRepositories);
  };
}
